### ISSUE TITLE
hdtSSEFramework.dll Crashing

### ISSUE THREAD

**Issue by Yankshuru** [HydrogensaysHDT/hdt-skyrimse-mods#3]
SKSE64 build 2.0.19

Framework build is 1.5.97

SKSE64.log:
checking plugin C:\Program Files (x86)\Steam\SteamApps\Common\SkyrimSpecialEdition\Data\SKSE\Plugins\\hdtSSEFramework.dll
plugin C:\Program Files (x86)\Steam\SteamApps\Common\SkyrimSpecialEdition\Data\SKSE\Plugins\\hdtSSEFramework.dll (00000001 hdtSSEFramework 00000001) disabled, fatal error occurred while loading plugin (handle 7)

![image](https://user-images.githubusercontent.com/10253991/92931390-c1bd7480-f419-11ea-9111-9d0cf32d1a90.png)

**Comment by Zhurama** [comment]
I have this error as well

**Comment by Rcott** [comment]
I also have this error...Skse64 has been updated several times and this is not keeping pace.

**Comment by Arlyana** [comment]
I am all so getting this error 
![Screenshot (12)](https://user-images.githubusercontent.com/22625245/99850964-250f0580-2b33-11eb-8af8-47520f1f74ac.png)
Skse64 is up to date.

**Comment by Rcott** [comment]
OK, it is not a problem from Skse64, It is because the files are no longer necessary if you updated HDTSSE to HDT-SMP for SSE as they are now built-in. To remove the error just navigate to your SKSE/Plugins folder and delete the two .dll's you see listed in the error message...
